### ISSUE TITLE
relup fail on second upgrade

### ISSUE THREAD

**Issue by benbro** [lrascao/rebar3_appup_plugin#39] opened 2018-02-23 16:50 UTC
I can do hot upgrade of a test app from version 0.1.0 to version 0.2.0 but generation of relup from version 0.2.0 to version 0.3.0 fails.

Steps to reproduce:
erlang/otp version 20.2
rebar3 version 3.5.0
rebar3_appup_plugin version 2.3.0

1. Create project.
```erlang
rebar3 new release mytest
```
2. Add rebar3_appup_plguin and provider_hooks to rebar.config
```erlang
{plugins, [rebar3_appup_plugin]}.

{provider_hooks, [
    {pre, [
        {tar, {appup, tar}}
    ]},
    {post, [
        {compile, {appup, compile}},
        {clean, {appup, clean}}
    ]}
]}.
```
3. Generate first release.
```
rebar3 as prod release
```
3.  Change release in rebar.config and app.src to 0.2.0
4. Create second release and upgrade.
```erlang
rebar3 as prod release
rebar3 as prod appup generate
rebar3 as prod relup
rebar3 as prod tar
```
5.  Change release in rebar.config and app.src to 0.3.0
6. Create third release and upgrade.
```erlang
rebar3 as prod release
rebar3 as prod appup generate --previous_version 0.2.0
rebar3 as prod relup
```
Error:
```
===> Errors generating relup 
          No release upgrade script entry for mytest-0.3.0 to mytest-0.2.0 in file mytest/_build/prod/rel/mytest/lib/mytest-0.3.0/ebin/mytest.appup
```

**Comment by lrascao** [comment] 2018-02-23 22:56
ah, i see the problem, the plugin sees an .appup that got generated when bumping from 0.1.0 to 0.2.0 so it won't try to generate anything:
````
{ "0.2.0",
    [{ "0.1.0",
        [] }],
    [{ "0.1.0",
        [] }]
}.
````
i guess the right thing to do here would be to generate the appup from 0.3.0 to 0.2.0 while still keeping the previous instructions

**Comment by benbro** [comment] 2018-07-14 13:44
Is there a workaround?
I've tried to delete mytest.appup from _build/prod/lib/mytest/ebin/mytest.appup and generate appup and call relup:
```
rebar3 as prod appup generate --previous_version 0.2.0
rebar3 as prod relup
```
But I'm getting an error:
```
===> Resolved mytest-0.3.0
===> Errors generating relup 
          Could not read file /home/me/test/mytest/_build/prod/rel/mytest/lib/mytest-0.3.0/ebin/mytest.appup
```

**Comment by benbro** [comment] 2018-07-14 13:54
It works if I manually delete mytest.appup from both places:
```
mytest/ _build/prod/lib/mytest/ebin/mytest.appup
mytest/_build/prod/rel/mytest/lib/mytest-0.2.0/ebin
```

**Comment by lrascao** [comment] 2018-07-14 22:51
you can try checking out 0.2.0, generate that release then check out 0.3.0 and request the appup generation from that version

**Comment by benbro** [comment] 2018-07-15 00:01
I'm generating the 0.3.0 appup from 0.2.0 but it fails:
```
rebar3 as prod appup generate --previous_version 0.2.0
```
The steps I'm using are in the first post. Isn't it how it supposed to work?
I don't understand how others manage to upgrade more than once.

**Comment by lrascao** [comment] 2018-10-03 13:29
duplicate of #49

**Comment by lrascao** [comment] 2018-10-03 13:30
#52 takes care of this, closing

**Closed by lrascao** 2018-10-03 13:30 UTC
